package yearsgen

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
)

// Generate scans the internal directory for year/day packages and writes the
// aggregator file that blank-imports each discovered package.
func Generate(root string) error {
	if root == "" {
		root = "."
	}
	internalPath := filepath.Join(root, "internal")
	years, err := discoverYears(internalPath)
	if err != nil {
		return err
	}

	destDir := filepath.Join(internalPath, "years")
	if err := os.MkdirAll(destDir, 0o755); err != nil {
		return err
	}
	destFile := filepath.Join(destDir, "years.gen.go")

	var buf bytes.Buffer
	buf.WriteString("// Code generated by yearsgen. DO NOT EDIT.\n")
	buf.WriteString("package years\n\n")
	buf.WriteString("import (\n")
	if len(years) == 0 {
		buf.WriteString("\t// no registered years yet\n")
	} else {
		for _, year := range years {
			fmt.Fprintf(&buf, "\t_ \"advent-of-code-go/internal/%d/day\"\n", year)
		}
	}
	buf.WriteString(")\n")

	return os.WriteFile(destFile, buf.Bytes(), 0o644)
}

func discoverYears(internalPath string) ([]int, error) {
	entries, err := os.ReadDir(internalPath)
	if err != nil {
		return nil, err
	}

	yearSet := make(map[int]struct{})
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		year, convErr := strconv.Atoi(entry.Name())
		if convErr != nil {
			continue
		}
		dayDir := filepath.Join(internalPath, entry.Name(), "day")
		info, statErr := os.Stat(dayDir)
		if statErr != nil || !info.IsDir() {
			continue
		}
		containsGo, err := hasGoFiles(dayDir)
		if err != nil {
			return nil, err
		}
		if containsGo {
			yearSet[year] = struct{}{}
		}
	}

	if len(yearSet) == 0 {
		return nil, nil
	}

	years := make([]int, 0, len(yearSet))
	for y := range yearSet {
		years = append(years, y)
	}
	sort.Ints(years)
	return years, nil
}

func hasGoFiles(dir string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return false, nil
		}
		return false, err
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if filepath.Ext(entry.Name()) == ".go" {
			return true, nil
		}
	}
	return false, nil
}
